---
- hosts: control
  vars_files:
    - ./vars/all_vars.yml
  user: ovh
  become: yes
  become_user: root
  tasks:
    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes
    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm
- hosts: control
  vars_files:
    - ./vars/all_vars.yml
  user: ovh
  become: yes
  become_user: root
  tasks:
    - name: Deploy python3
      package:
        name: python3
        state: present
    - name: Deploy pip3
      package:
        name: python3-pip
        state: present
    - name: Install community.kubernetes.k8s python dependencies
      pip:
        name:
          - openshift>=0.12.0,<0.13.0
    - name: Add storage role to pods
      k8s:
        definition:
          apiversion: v1
          kind: Node
          metadata:
            name: "{{item}}"
            labels:
              node-role.kubernetes.io/storage-node: ""
      with_items:
        - main1
        - main2
        - main3
    # - name: Check if tiller is installed
    #   shell: kubectl get pods --namespace kube-system | grep -q tiller
    #   register: tillerInstalled
    #   failed_when: false
    # - name: Run helm init to install tiller
    #   shell: helm init
    #   when: tillerInstalled.rc > 0
    # - name: Deploy tiller service account
    #   community.kubernetes.k8s:
    #     state: present
    #     definition: "{{ lookup('file', './files/tiller/serviceaccount.yml') | from_yaml }}"
    # - name: Deploy tiller CRB
    #   community.kubernetes.k8s:
    #     state: present
    #     definition: "{{ lookup('file', './files/tiller/clusterrolebinding.yml') | from_yaml }}"
    
    - name: Add rook repository
      community.kubernetes.helm_repository:
        name: release
        repo_url: https://charts.rook.io/release
    - name: Deploy rook-ceph chart
      community.kubernetes.helm:
        name: rook-ceph
        chart_ref: release/rook-ceph
        release_namespace: rook-ceph
        create_namespace: yes
    - name: Deploy rook-ceph storage class
      community.kubernetes.k8s:
        state: "{{rook_state}}"
        definition: "{{ lookup('file', './files/ceph/storageclass.yml') | from_yaml }}"
    - name: Deploy rook-ceph replica pool
      community.kubernetes.k8s:
        state: "{{rook_state}}"
        definition: "{{ lookup('file', './files/ceph/replicapool.yml') | from_yaml }}"
    - name: Deploy rook-ceph storage cluster
      community.kubernetes.k8s:
        state: "{{rook_state}}"
        definition: "{{ lookup('file', './files/ceph/deployment.yml') | from_yaml }}"
    - name: Deploy rook-ceph toolbox
      community.kubernetes.k8s:
        state: "{{rook_state}}"
        definition: "{{ lookup('file', './files/ceph/toolbox.yml') | from_yaml }}"